name: aion
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #
  cupertino_icons: ^1.0.2
  #
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cubit_form: ^2.0.1
  #
  carousel_slider: ^4.1.1
  #
  flutter_svg: ^1.0.3
  # internet uchun
  connectivity_plus: ^2.3.0
  #
  animate_do: ^2.1.0
  #
  filter_list: ^1.0.1
  #
  cupertino_tabbar: ^2.0.0
  #
  google_fonts: ^2.3.2
  #
  equatable: ^2.0.3
  # timer uchun
  slide_countdown: ^0.2.4
  # imgni cached qilish uchun
  cached_network_image: ^3.2.0
  #
  url_launcher: ^6.1.2
  #
  image_picker: ^0.8.5+3
  #
  country_code_picker: ^2.0.2
  #
  pinput: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf
    - family: Mer
      fonts:
        - asset: assets/fonts/merriweather.ttf

